[tox]
package_name = "steam_client"
envlist = lint, type, py{311,312,313,314}

[testenv]
deps = pytest
commands =
    pytest {posargs:tests}

[testenv:lint]
description = Run all linting checks
skip_install = true
deps =
    flake8
    flake8-markdown
commands = flake8 {[tox]package_name}
           flake8 --extend-ignore=E999,F821 README.md

[testenv:type]
description = Run all type checks
skip_install = true
deps = mypy
commands = mypy {[tox]package_name}

[gh-actions]
python =
    3.11: lint, type, py311
    3.12: py312
    3.13: py313
    3.14: py314